### ISSUE TITLE
Support for LSDJ Midi Commands

### ISSUE THREAD

**Issue by peterswimm** [alexras/lsmc#12]
Please allow the reading and writing of instruments that use LSDJ Midi out commands:

https://code.google.com/p/arduinoboy/

    N - Sends a MIDI Note - Absolute to the value placed in the effect. N00 sends note off, N01-N6F send notes 1 to 112.
    Q - Sends a MIDI Note relative to the current channel's pitch. The effect value is a offset. so Q0C in PU1 would send a note 1 octave higher than what Pu1 is currently playing. This is useful as a table command to track midi notes as normal notes in the sequencer.
    X - Sends a MIDI CC - By default in Arduinoboy the high nibble selects a CC#, and the low nibble sends a value [0-F] to [0-127]. This can be changed to allow just 1 midi CC with a range of 00-6F, or 7 CCs with scaled or unscaled values.
    Y - Sends a program/patch/preset change.

**Comment by alexras** [comment]
Well, better late than never ...

I just tested loading a .sav file with Arduinoboy commands in one of its phrases on the just-released version 1.1b, and it worked. So if you still care, and want to give it a try, please do!
