### ISSUE TITLE
Mac dependencies out of date

### ISSUE THREAD

**Issue by clickysteve** [alexras/lsmc#14]
I'm hitting the following error when trying to run 'make install-deps mac'

>   Could not find a version that satisfies the requirement wxPython>=3.0 (from -r ../requirements.txt (line 2)) (from versions: )
No matching distribution found for wxPython>=3.0 (from -r ../requirements.txt (line 2))

Is the requirements file out of date?

**Comment by clickysteve** [comment]
Update: 

Same issue with:

> ObjectListView == 1.2

I installed the dependencies manually, but am now getting the following error: 

> /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/tools/img2py.py': [Errno 2] No such file or directory

which is probably down to something I've done...

**Comment by alexras** [comment]
In retrospect, that path is awfully specific ... you should be able to set `IMG2PY_SCRIPT` in `lsmc/images/make_images.sh` to `/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/tools/img2py.py` to unstick it.

I haven't built lsmc on El Capitan yet (haven't really had the time to work on this in a while). If I get the cycles in the next week or so, I'll give it a shot. It sounds like you're close, though.

**Comment by clickysteve** [comment]
Aha, looks like there's some problems with El Capitan and wxPython - even when built manually, or maybe it's just me. Even though Python and exPython were installed, the paths above weren't present. 

I ended up downloading Brew and re-installing both (in order), which created the necessary folders.

I still ran into the problem when using 'make build-mac', but adjusting the path like you said worked grand!

Ran into another error when trying to launch the app though. A popup appears saying: "LSMC Error", with an option to either Terminate or Open the Console.

Console log:

> 22/02/2016 18:20:41.332 LSMC[22552]: 2016-02-22 18:20:41.331 LSMC[22552:1509591] LSMC Error
22/02/2016 18:21:09.939 LSMC[22578]: Traceback (most recent call last):
22/02/2016 18:21:09.939 LSMC[22578]:   File "/Users/Steve/Music/Music Making/Apps/lsmc-master/lsmc/dist/LSMC.app/Contents/Resources/__boot__.py", line 103, in <module>
22/02/2016 18:21:09.939 LSMC[22578]:     _run()
22/02/2016 18:21:09.939 LSMC[22578]:   File "/Users/Steve/Music/Music Making/Apps/lsmc-master/lsmc/dist/LSMC.app/Contents/Resources/__boot__.py", line 88, in _run
22/02/2016 18:21:09.939 LSMC[22578]:     exec(compile(source, path, 'exec'), globals(), globals())
22/02/2016 18:21:09.939 LSMC[22578]:   File "/Users/Steve/Music/Music Making/Apps/lsmc-master/lsmc/dist/LSMC.app/Contents/Resources/LSMC", line 3, in <module>
22/02/2016 18:21:09.939 LSMC[22578]:     import wx, functools, event_handlers
22/02/2016 18:21:09.939 LSMC[22578]:   File "event_handlers.pyc", line 7, in <module>
22/02/2016 18:21:09.939 LSMC[22578]:   File "utils.pyc", line 4, in <module>
22/02/2016 18:21:09.939 LSMC[22578]:   File "ObjectListView/__init__.pyc", line 22, in <module>
22/02/2016 18:21:09.939 LSMC[22578]:   File "ObjectListView/ObjectListView.pyc", line 105, in <module>
22/02/2016 18:21:09.939 LSMC[22578]: ImportError: No module named six
22/02/2016 18:21:10.067 LSMC[22578]: LSMC Error
22/02/2016 18:21:10.067 LSMC[22578]: 2016-02-22 18:21:10.066 LSMC[22578:1510336] LSMC Error

Hopefully I'm just doing something dumb.

**Comment by alexras** [comment]
So sorry for not getting to this sooner.

I just pushed a change that should fix builds in El Capitan; if you still care, let me know if it works for you.
