### ISSUE TITLE
Rename to LSMC breaks py2app

### ISSUE THREAD

**Issue by SixWays** [alexras/lsmc#9]
py2app fails saying "TypeError: Don't know how to handle 'LSMC'". Seems to just be objecting to not having the .py extension. Going back two revisions (to 77b7e6c1a151c7dea3bff68d8b358672b4578723) fixes issue.

**Comment by alexras** [comment]
Looks to be working in c2d114a. Thanks for reporting; sorry this has been open for so many months!
